require('plugins')
require('pkeys')

require('lsp.mason')
require('lsp.lsp')
require('lsp.cmp')
require('config.tree')
require('config.text')
require('config.telescope')
require('config.term')
require('config.vim_go')
require('config.themes').one()
require('config.markdown')
require('config.treesitter').langlist({ 'c', 'vim', 'lua', 'help', 'rust', 'c', 'go' })
